//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultNumberValidity
    {
        public System.Guid Id { get; set; }
        public System.Guid PlaceId { get; set; }
        public System.Guid DefaultNumberId { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public bool IsSecondary { get; set; }
        public Nullable<byte> Osd { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
    
        public virtual UesPlace UesPlace { get; set; }
        public virtual DefaultNumber DefaultNumber { get; set; }
    }
}
