//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UesBasePoint
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UesBasePoint()
        {
            this.EntityBasePoints = new HashSet<BasePoint>();
            this.UesPlace = new HashSet<UesPlace>();
        }
    
        public System.Guid Id { get; set; }
        public string BasePointId { get; set; }
        public string DealCode { get; set; }
        public byte Type { get; set; }
        public string TownCode { get; set; }
        public string LightTownCode { get; set; }
        public string Address { get; set; }
        public string SiteUrl { get; set; }
        public string PlaceCode { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Email { get; set; }
        public string PhoneCode { get; set; }
        public string PhoneNumber { get; set; }
        public string FaxCode { get; set; }
        public string FaxNumber { get; set; }
        public string ContactSiteUrl { get; set; }
        public bool IncludeInReceipt { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public System.DateTime ValidTo { get; set; }
        public byte SaleType { get; set; }
        public bool IsSeaRateReg { get; set; }
        public Nullable<System.DateTime> SeaRegFrom { get; set; }
        public Nullable<System.DateTime> SeaRegTo { get; set; }
        public Nullable<System.Guid> SubDealId { get; set; }
        public Nullable<System.Guid> NsBasePointId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public bool IsMerch { get; set; }
        public string AddressLatin { get; set; }
        public string RevokedByRequestNumber { get; set; }
        public Nullable<System.Guid> RevokedByCorrelationId { get; set; }
        public string RevokedByBsProcessCode { get; set; }
        public string RevokedByDisplayName { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedByBsProcessCode { get; set; }
        public string CreatedByRequestNumber { get; set; }
        public Nullable<System.Guid> CreatedByCorrelationId { get; set; }
        public string CrimeaLightTownCode { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Town Town { get; set; }
        public virtual Town LightTown { get; set; }
        public virtual BasePoint EntityBasePoint { get; set; }
        public virtual Town CrimeaLightTown { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BasePoint> EntityBasePoints { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UesPlace> UesPlace { get; set; }
    }
}
