//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UesPlace
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UesPlace()
        {
            this.DefaultNumberValidity = new HashSet<DefaultNumberValidity>();
            this.UADefaultNumberValidity = new HashSet<UADefaultNumberValidity>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string CorpCode { get; set; }
        public byte CorpQualifier { get; set; }
        public string PlaceId { get; set; }
        public string PlaceTypeCode { get; set; }
        public int PlaceType { get; set; }
        public int SystemType { get; set; }
        public bool UA { get; set; }
        public string DutyCode { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<System.Guid> ConfigurationTemplateId { get; set; }
        public string Vendor { get; set; }
        public string Action { get; set; }
        public string Ity { get; set; }
        public string AgentCode { get; set; }
        public Nullable<System.Guid> BasePointId { get; set; }
        public string Comment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public string Address_tmp { get; set; }
        public string StcCode { get; set; }
        public Nullable<byte> ConnectionType { get; set; }
        public Nullable<System.Guid> NsPlaceId { get; set; }
        public Nullable<System.Guid> NsBasePointId { get; set; }
        public string CountryCode { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public bool IsBlock { get; set; }
        public bool SellingPlace { get; set; }
        public Nullable<byte> SiteAudience { get; set; }
        public bool ARDWeb { get; set; }
        public bool HasSmartTicketingSales { get; set; }
        public bool IsSubAgentTicketIssuanceProhibited { get; set; }
        public bool BlockchainSaleAllowed { get; set; }
        public string RevokedByRequestNumber { get; set; }
        public Nullable<System.Guid> RevokedByCorrelationId { get; set; }
        public string RevokedByBusinessProcessCode { get; set; }
        public string RevokedByDisplayName { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedByBusinessProcessCode { get; set; }
        public string CreatedByRequestNumber { get; set; }
        public Nullable<System.Guid> CreatedByCorrelationId { get; set; }
        public bool IsTest { get; set; }
        public bool IsCharter { get; set; }
    
        public virtual Organization Organization { get; set; }
        public virtual Stc Stc { get; set; }
        public virtual BasePoint BasePoint { get; set; }
        public virtual UesBasePoint UesBasePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DefaultNumberValidity> DefaultNumberValidity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UADefaultNumberValidity> UADefaultNumberValidity { get; set; }
    }
}
