//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityExpiration
    {
        public System.Guid EntityExpirationGuid { get; set; }
        public System.Guid MainPointGuid { get; set; }
        public System.Guid EntityGuid { get; set; }
        public Nullable<System.DateTime> ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string ModifiedBy { get; set; }
        public string Letters { get; set; }
    
        public virtual MainPoint EntityMainPoint { get; set; }
        public virtual Entity Entity { get; set; }
    }
}
