//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntityContext : DbContext
    {
        public EntityContext()
            : base("name=EntityContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EusMainPoint> EusMainPoint { get; set; }
        public virtual DbSet<Agent> Agent { get; set; }
        public virtual DbSet<AgentCurrency> AgentCurrency { get; set; }
        public virtual DbSet<Agreement> Agreement { get; set; }
        public virtual DbSet<City> City { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Organization> Organization { get; set; }
        public virtual DbSet<Lt> Lt { get; set; }
        public virtual DbSet<Region> Region { get; set; }
        public virtual DbSet<MainPoint> MainPoint { get; set; }
        public virtual DbSet<UserSettings> UserSettings { get; set; }
        public virtual DbSet<Entity> Entity { get; set; }
        public virtual DbSet<EntityExpiration> EntityExpiration { get; set; }
        public virtual DbSet<EusPlace> EusPlace { get; set; }
        public virtual DbSet<RnOffc> RnOffc { get; set; }
        public virtual DbSet<DefaultNumber> DefaultNumber { get; set; }
        public virtual DbSet<DefaultNumberValidity> DefaultNumberValidity { get; set; }
        public virtual DbSet<UADefaultNumber> UADefaultNumber { get; set; }
        public virtual DbSet<UADefaultNumberValidity> UADefaultNumberValidity { get; set; }
        public virtual DbSet<MainPointType> MainPointType { get; set; }
    }
}
