//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ep()
        {
            this.SrnTaps = new HashSet<SrnOffc>();
        }
    
        public System.Guid EpGuid { get; set; }
        public Nullable<System.Guid> BasePointGuid { get; set; }
        public string EpSystem { get; set; }
        public string OFFC { get; set; }
        public System.DateTime AutorizeDate { get; set; }
        public string AK { get; set; }
        public bool EMD { get; set; }
        public string Comment { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<bool> Status { get; set; }
        public bool IsNew { get; set; }
        public string GRP { get; set; }
        public string AGN { get; set; }
        public string PID { get; set; }
        public string PIDType { get; set; }
        public string PlaceName { get; set; }
        public string Address { get; set; }
        public string Letter { get; set; }
        public Nullable<bool> SRDT { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public string RMK { get; set; }
        public string CUST { get; set; }
        public string ZZ { get; set; }
        public string ExecutionCode { get; set; }
        public string ASIACode { get; set; }
        public string PlaceId { get; set; }
        public bool IsTraining { get; set; }
        public string TrainingVal { get; set; }
        public Nullable<System.Guid> MasterPIDGuid { get; set; }
        public bool IsOnline { get; set; }
        public string CustomDealCode { get; set; }
        public Nullable<System.Guid> CustomSubDealGuid { get; set; }
        public string CustomDeal { get; set; }
        public Nullable<bool> AKSPayment { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Hrdt { get; set; }
        public bool Api { get; set; }
        public bool Sws { get; set; }
        public bool SrnStatus { get; set; }
        public System.DateTime ValidFrom { get; set; }
        public Nullable<System.DateTime> ValidTo { get; set; }
        public string RevokedByRequestNumber { get; set; }
        public Nullable<System.Guid> RevokedByCorrelationId { get; set; }
        public string RevokedByBsProcessCode { get; set; }
        public string RevokedByDisplayName { get; set; }
        public string CreatedByDisplayName { get; set; }
        public string CreatedByBsProcessCode { get; set; }
        public string CreatedByRequestNumber { get; set; }
        public Nullable<System.Guid> CreatedByCorrelationId { get; set; }
    
        public virtual Deal Deal { get; set; }
        public virtual BasePoint EntityBasePoint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SrnOffc> SrnTaps { get; set; }
    }
}
