//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Deal()
        {
            this.Agreement = new HashSet<Agreement>();
            this.Lt = new HashSet<Lt>();
            this.MainPoint = new HashSet<MainPoint>();
        }
    
        public string Code { get; set; }
        public string TKP { get; set; }
        public string SalesType { get; set; }
        public string Accreditation { get; set; }
        public Nullable<System.Guid> WarrantyGuid { get; set; }
        public string ContractNumber { get; set; }
        public string Delivery { get; set; }
        public Nullable<decimal> MaxBCO { get; set; }
        public bool IsNotShowCCR { get; set; }
    
        public virtual Organization Organization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Agreement> Agreement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lt> Lt { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainPoint> MainPoint { get; set; }
    }
}
