//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RnOffc
    {
        public System.Guid RnOffcGuid { get; set; }
        public System.Guid LtGuid { get; set; }
        public string Offc { get; set; }
    
        public virtual Lt Lt { get; set; }
    }
}
