//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity.DataAccess
{
    using System;
    
    public enum SystematicType : byte
    {
        Default = 0,
        EusET = 1,
        ElioET = 2,
        Srn = 3,
        SabreET = 4,
        EusTest = 5
    }
}
